ALTER TABLE `blog`.`login`
    CHANGE COLUMN `password` `password`     VARCHAR(45) NOT NULL,
    CHANGE COLUMN `created_at` `created_at` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHANGE COLUMN `updated_at` `updated_at` TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
